'use client'

import Image from 'next/image'
import { useEffect, useState } from 'react'
import { DotPattern } from '@/components/ui/dot-pattern'
import { cn } from '@/lib/utils'
import { CloudinaryPicture } from './cloudinary-picture'
import breakpointsData from '@/data/cloudinary-breakpoints.json'

// Generated by `pnpm cloudinary:breakpoints`; keyed by Cloudinary public ID.
const breakpointsMap: Record<string, number[]> = breakpointsData

/**
 * Map a local image path to a Cloudinary public ID.
 *
 * Examples:
 *   /thumbnails/foo.jpg        → thumbnails/foo
 *   public/thumbnails/foo.jpg  → thumbnails/foo
 *   assets/images/bar.png      → assets/images/bar
 */
function localPathToPublicId(src: string): string | null {
  const clean = src
    .replace(/^\/+/, '')         // strip leading slashes
    .replace(/^public\//, '')    // strip public/ prefix
    .replace(/\.[^/.]+$/, '')    // strip file extension
    .replace(/\/+/g, '/')        // normalise double-slashes
  return clean || null
}

interface PostImageProps {
  src?: string
  alt: string
  width?: number
  height?: number
  placeholder?: string
  sizes?: string
  loading?: 'lazy' | 'eager'
  /** Set true for the LCP / hero image: eager loading + fetchPriority=high */
  priority?: boolean
  unoptimized?: boolean
  hoverScale?: boolean
  className?: string
  pictureClass?: string
}

export function PostImage({
  src,
  alt,
  width,
  height,
  placeholder,
  sizes = '(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw',
  loading = 'lazy',
  priority = false,
  unoptimized = false,
  hoverScale = false,
  className,
  pictureClass,
}: PostImageProps) {
  const [loaded, setLoaded] = useState(false)
  const [error, setError] = useState(false)

  useEffect(() => {
    setLoaded(false)
    setError(false)
  }, [src])

  // 1. No source → placeholder
  if (!src || src === '') {
    return (
      <div
        className={cn(
          'relative w-full h-full flex items-center justify-center bg-muted',
          className,
        )}
      >
        {placeholder && (
          <span className="text-sm text-muted-foreground">{placeholder}</span>
        )}
      </div>
    )
  }

  // 2. Derive Cloudinary public ID from the local path.
  //    If a matching entry exists in the breakpoints map, serve a full
  //    responsive <picture> with JXL → AVIF → WebP sources.
  //    If the public ID can be derived but breakpoints are missing, we still
  //    route through CloudinaryPicture which falls back to a single f_auto URL.
  const publicId = localPathToPublicId(src)

  if (publicId) {
    const bp = breakpointsMap[publicId]
    return (
      <CloudinaryPicture
        src={publicId}
        alt={alt}
        width={width}
        height={height}
        sizes={sizes}
        breakpoints={bp}
        priority={priority}
        pictureClass={pictureClass}
        className={cn(
          'transition-transform duration-300',
          hoverScale && 'group-hover:scale-105',
          className,
        )}
      />
    )
  }

  // 3. Fallback: standard Next.js Image for images not in the Cloudinary pipeline.
  return (
    <>
      {!loaded && (
        <>
          <DotPattern
            width={20}
            height={20}
            cx={1}
            cy={1}
            cr={1}
            className={cn(
              'fill-muted-foreground/20 transition-transform duration-300',
              hoverScale && 'group-hover:scale-105',
            )}
          />
          {placeholder !== undefined && placeholder !== '' && (
            <span className="text-muted-foreground absolute inset-0 flex items-center justify-center text-sm">
              {placeholder}
            </span>
          )}
        </>
      )}
      {!error && (
        <Image
          src={src}
          alt={alt}
          fill
          sizes={sizes}
          loading={priority ? 'eager' : loading}
          priority={priority}
          unoptimized={unoptimized}
          className={cn(
            'object-cover transition-transform duration-300',
            hoverScale && 'group-hover:scale-105',
            className,
          )}
          onLoad={() => setLoaded(true)}
          onError={() => setError(true)}
        />
      )}
    </>
  )
}
